### ISSUE TITLE
Linux: Support ARM architecture

### ISSUE THREAD

**Issue by COx2** [Live2D/CubismNativeComponents#1]
Would it be possible to have a release for Linux arm? 
I want to running the Cubism Apps on Raspberry Pi 2/3 with Raspbian.
https://en.wikipedia.org/wiki/Raspberry_Pi
Thanks.

**Comment by andi-at-live2d-com** [comment]
I must confess Raspberry PI wasn't on our list of platforms we planned to support... but, hey, why not?
I'm not familiar with the Raspberry at all, but I build the Core using [this toolchain](https://github.com/raspberrypi/tools/tree/master/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf) and updated the package you can download from [here](https://live2d.github.io/index.html#native). You'll find the libraries in `lib/experimental/rpi`. It would be great if you could post how your small adventure went ;) .
(Be aware that the OpenGLES 2.0 rendering is also still somewhat experimental)...
Please note that we have holidays here in Japan till the end of this week, so please excuse any late responses from my site in advantage.

**Comment by COx2** [comment]
Thank you for your support.
I had try to build Sample Projects in this repository with Cubism-Core-Library(latest).
It's work fine!!! That's great.

![rpi_cubism](https://cloud.githubusercontent.com/assets/2960956/26032635/45e5aca6-38d3-11e7-8009-fdb07ddd1439.gif)

I would describe the recipe below:

- OS: RASPBIAN JESSIE WITH PIXEL(latest)
- Machine: Raspberry Pi2

Updating and Upgrading Raspbian.
```
$sudo apt-get update
$sudo apt-get upgrade
$reboot
```
Install the CMake tools.
```
$sudo apt-get install cmake
$sudo apt-get install cmake-gui       // if you needed
```

Install the OpenGL library.
`$sudo apt-get install freeglut3-dev`

1. Download Cubism 3 SDK Core
2. download CubismNativeComponents
3. Download SDL2-2.0.5
4. Copy Cubism 3 SDK Core to CubismNativeComponents folder
5. Modify the `CubismNativeComponents/CMakeLists.txt` as below.

at line 7, I add linker direcories specified for Raspbian. 
` link_directories(/opt/vc/lib)`
 
at line355. I modify like below. (not clever...)
>(original) 
>```
>   if (_CSM_BUILD_DEVELOP)
>     set(_CSM_CORE_LIB_DIR ${_CSM_CORE_ROOT_DIR}/lib/develop)
>   else ()
>     set(_CSM_CORE_LIB_DIR ${_CSM_CORE_ROOT_DIR}/lib/release)
>   endif ()
> ```
> 
> (modified)
> ```
>   if (_CSM_BUILD_DEVELOP)
>     set(_CSM_CORE_LIB_DIR ${_CSM_CORE_ROOT_DIR}/lib/develop)
>     set(_CSM_CORE_LIB_DIR_EXP ${_CSM_CORE_ROOT_DIR}/lib/experimental/develop)
>   else ()
>     set(_CSM_CORE_LIB_DIR ${_CSM_CORE_ROOT_DIR}/lib/release)
>     set(_CSM_CORE_LIB_DIR_EXP ${_CSM_CORE_ROOT_DIR}/lib/experimental/release)
>   endif ()
> ```

at line374.
>(original) 
> ```
>   elseif (LINUX AND (CMAKE_SIZEOF_VOID_P EQUAL 8))
>     set(_CSM_CORE_LIB_DIR ${_CSM_CORE_LIB_DIR}/linux/x86_64)
>   else ()
>     message(FATAL_ERROR "Building samples for target platform not supported.")
>   endif ()
> ```
> 
>(modified)
> ```
>   elseif (LINUX AND (CMAKE_SIZEOF_VOID_P EQUAL 8))
>     set(_CSM_CORE_LIB_DIR ${_CSM_CORE_LIB_DIR}/linux/x86_64)
>   elseif (LINUX)
>     set(_CSM_CORE_LIB_DIR ${_CSM_CORE_LIB_DIR_EXP}/rpi/arm-rpi-4.9.3-linux-gnueabihf)
>   else ()
>     message(FATAL_ERROR "Building samples for target platform not supported.")
>   endif ()
> ```

Execute CMake operations at CubismNativeComponents directory.
- Configure
 ・Unix Makefiles
 ・Use default native components
- Generate
  ・If work fine, the Makefile will created.

Execute make operations at build directory(CMake option).
`$sudo make`

**Comment by andi-at-live2d-com** [comment]
@COx2 Hey, thanks for trying the stuff out and for posting such a great recipe! I'll see if I can get my hands on a Raspberry to update and test the CMake project. (Please allow me to close this issue in the meantime).
