### ISSUE TITLE
csmVertexPositionsDidChange never resets

### ISSUE THREAD

**Issue by Nisiii** [Live2D/CubismNativeComponents#11]
Hello,
I'm new to github or at least never used it to post something as an issue before. Please let me know if this isn't the place for this kind of questions.

Like I posted before to the live2d community board ( http://community.live2d.com/discussion/521/csmvertexpositionsdidchange-never-resets-cubism3-0-native#latest ) I have a problem that I didn't understand regarding the SDK and also with the implementation of the CubismNativeComponent project.

I implemented the cubism sdk 3.0 into my own project (C++, Cocos2dx) with custom rendering and also with my own base implementation of the animation with the CubismNativeComponent project as a reference.

What I didn't understand is, that IsBitSet(dynamicFlags[i], csmVertexPositionsDidChange	); is set every time/frame for each element. Even if I do not update any animation curves. 

```
// Update model.
csmUpdateModel(Sample.Model);
// Update renderer.
csmUpdateGlRenderer(Sample.Renderer);
// Reset dynamic drawable flags.
smResetDrawableDynamicFlags(Sample.Model);
// Draw.
csmGlDraw(Sample.Renderer, GetViewProjectionMatrix(), &Sample.Texture);
```
1. Call csmUpdateModel()
2. Update vertices if csmVertexPositionsDidChange is set (and more)
3. Call csmResetDrawableDynamicFlags for model
4. Render

In my understanding point 3 should reset the flags and if I don't do anything the flag should never reappear. 
If i do not call csmResetDrawableDynamicFlags all flags for each drawable are 63 and they never change (of course, because I do not call ResetDrawableDynamicFlag). If I call csmResetDrawableDynamicFlags after each update and before rendering the flags are always 33 and that tells me that the VertexPostionChanged flag is set all the time. Did I miss something?

**Comment by itoh-at-live2d-com** [comment]
@Nisiii 
Hi.

Thanks for posting!

>What I didn't understand is, that IsBitSet(dynamicFlags[i], csmVertexPositionsDidChange	); is set every time/frame for each element. Even if I do not update any animation curves.

The csmVertexPositionsDidChange flag sets true if any artmeshes is exist.
It means, the calculations and updates are no related to csmVertexPositionsDidChange flag.
If you didn't call csmResetDrawableDynamicFlags(), NativeCore sets only csmIsVisible flag when any artmeshes aren't transparent.

**Comment by Nisiii** [comment]
Ah, I see. I have misinterpreted this flag. Thank you for clarification.

Now, in my understanding it looks like it is very unusual that there are no updates on the vertices because the whole model is animated anyways in most cases. Am I right? So a check shouldn't be necessary or if I want to implement it I need to do it by myself?!

**Comment by itoh-at-live2d-com** [comment]
@Nisiii 
It's too heavy to check all vertices changing to set the flag.
So, we skip checking vertices changing and set flag if vertices are possibility changing.
...Did I answer your question?

**Comment by Nisiii** [comment]
Yes, thank you very much!
