### ISSUE TITLE
How can I integrate live2d into iOS App?

### ISSUE THREAD

**Issue by niyaoyao** [Live2D/CubismNativeComponents#12]
I am searching for more guides for integrating live2d SDK for iOS App. However, the [CubismNativeComponents](https://github.com/Live2D/CubismNativeComponents/issues/new) project description is not detailed enough for me to build an iOS App. Can you provide a more detailed tutorial for integrating iOS App ?

**Comment by niyaoyao** [comment]
When I build Components with CMake error occurred

```
CMake Error at CMakeLists.txt:93 (if):
  if given arguments:

    "_CSM_COMPONENTS_GL_H" "AND" "(" "NOT" "EXISTS" "OR" "IS_DIRECTORY" ")"

  Unknown arguments specified


Configuring incomplete, errors occurred!
```

**Comment by itoh-at-live2d-com** [comment]
@niyaoyao 
Hi.
To building for iOS, it can't use CMake.
And, you can see "Building iOS" section in [Readme.md](https://github.com/Live2D/CubismNativeComponents/blob/develop/Readme.md).

**Comment by niyaoyao** [comment]
@itoh-at-live2d-com 

> First build the sample for your host to make sure you have all dependencies required.

How can I build the sample besides using CMake?

**Comment by itoh-at-live2d-com** [comment]
@niyaoyao 
Build the sample for your host using CMake to check all dependencies required.
And, you have to port iOS. It isn't use CMake, it use SDL2 iOS Template that is built before in your host.
...Did I answer your question?

**Comment by niyaoyao** [comment]
@itoh-at-live2d-com  Thanks a lot. I'll try it.
