### ISSUE TITLE
Needs SDK 3.0 Guides and project demo for iOS development 

### ISSUE THREAD

**Issue by niyaoyao** [Live2D/CubismNativeComponents#13]
I explore the live2d.com for SDK 3.0  tutorials/guides for iOS development. It seems that it only provide tutorial for Unity.

I've downloaded the SDK on https://live2d.github.io/#native , however , I can't find any demo for developing. Can you provide more resources about that?

**Comment by niyaoyao** [comment]
When could you provide a demo for SDK 3.0? @itoh-at-live2d-com  @nakamura-at-live2d-com @ono-at-live2d-com

**Comment by itoh-at-live2d-com** [comment]
@niyaoyao 
Did you try [this](https://github.com/Live2D/CubismNativeComponents/issues/12)?
It is a simple sample demo including for iOS.

**Comment by niyaoyao** [comment]
I have tried a lot , it doesn't worked. And it occur lots of issues. Such as,
"/Users/niyao/N.Y./Projects/Apple/emotion-kit/SDL/SDL iOS Application/Live2DSDK3.0/Components/sample/src/Asset.c:21:10: 'stb_image.h' file not found"

**Comment by niyaoyao** [comment]
I followed the guide for iOS integration, and build SDL template project successfully. Then, I add the sources into project as group, add search header files and library search paths  in the build setting's tab. 

However, the project run failed.
@itoh-at-live2d-com

**Comment by niyaoyao** [comment]
I think it is too complex for developers to integrate SDK 3.0 into native project compare with SDK 2.0.

@itoh-at-live2d-com

**Comment by niyaoyao** [comment]
Well, I have found the solution by myself. I must download the stb-master files into ./Components/sample/vendor/stb-master .

Thank you all the same.

**Comment by niyaoyao** [comment]
And another question come up with the SDL project demo. I am doubt that how can I use the project in my App work together with UIKit.  

Within SDK 2.0, I just rerender GLKView , and set model in the delegate. How does SDK 3.0 work with UIKit?

**Comment by niyaoyao** [comment]
Can I use Live2d 3.0 SDK to develop native App without  SDL framework? @itoh-at-live2d-com 
Such as,  Apple Cocoa Touch framework or Android NDK ?

**Comment by dylanNew** [comment]
@niyaoyao I have created a demo base on  openGL, you can try this demo without SDL.Although there are a lot of bugs， you can try it  [https://github.com/dylanNew/live2d-demo](url)

**Comment by niyaoyao** [comment]
@dylanNew  Thanks, but the demo page has 404.

**Comment by dylanNew** [comment]
@niyaoyao  https://github.com/dylanNew/live2d-demo fixed

**Comment by niyaoyao** [comment]
@dylanNe Thanks a lot! It's worked!
