### ISSUE TITLE
how can we get canvas witdh and height?

### ISSUE THREAD

**Issue by HamAndBean** [Live2D/CubismNativeComponents#16]
how can we get model canvas witdh and height? In sdk2 ,we use live2DModel->getCanvasWidth() live2DModel->getCanvasHeight()

**Comment by itoh-at-live2d-com** [comment]
@HamAndBean 
Hi, I'm sorry for late.
To get canvas information, You can use `csmReadCanvasInfo()` function in Live2DCubismCore.h.
