### ISSUE TITLE
Error in Cmake

### ISSUE THREAD

**Issue by tohsssik** [Live2D/CubismNativeComponents#2]
Hi!
I met a problem when trying to build the program following your instruction.
I put the Cubism Core and SDL2 to correct place , and run Cmake , then the error occurs:

CMake Error at D:/program files/Cmake3.8/share/cmake-3.8/Modules/ExternalProject.cmake:1805 (message):
  error: could not find git for clone of Stb
Call Stack (most recent call first):
  D:/program files/Cmake3.8/share/cmake-3.8/Modules/ExternalProject.cmake:2560 (_ep_add_download_command)
  CMakeLists.txt:290 (ExternalProject_Add)

How can I solve this problem ?
Or if I want to use live2d for windows developing, any other ideas?
Thank you in advance!

**Comment by tohsssik** [comment]
Sorry my fault .
I forgot to restart cmake after installing the git....
problem solved!
(But I don't know how to delete the issue……

**Comment by andi-at-live2d-com** [comment]
Hey,


thanks for solving your own issue! I updated the readme of the project so it is more clear that `git` is also needed for building the samples, so please allow me to close this issue.
