### ISSUE TITLE
Cubism 3 components samples for iOS and Android

### ISSUE THREAD

**Issue by JiarongYu** [Live2D/CubismNativeComponents#3]
When will you release the iOS and Android samples?
Our company want to test cubism 3 SDK in mobile product.

**Comment by andi-at-live2d-com** [comment]
Hey,


thanks for your interest in Cubism3. If you want to roll out your own rendering, then everythings already ready for mobile. Core libraries are already included, and the components should compile, too. (The samples might actually work, too, with some effort though)...

Testing the components on mobile and providing instructions on how to build them for mobile should become end of May/beginning of June for us. I hope that's feasible for you.

**Comment by JiarongYu** [comment]
Thanks!
Cubism3 is great.  We hope to test your components on mobile ASSP, and use it in our mobile product.

**Comment by itoh-at-live2d-com** [comment]
@JiarongYu 
I just pushed fixes and instructions on how to build the samples on Android - masking is still WIP, but I wanted to allow you to try the stuff at least on one mobile platform ahead of @andi-at-live2d-com's schedule ;).

**Comment by andi-at-live2d-com** [comment]
@JiarongYu 
Ok, it took longer than expected to test the sample on iOS, too, and provide instructions, but I just pushed the whole mess ;) . Hope I'm not to late to the party...

**Comment by JiarongYu** [comment]
@andi-at-live2d-com 
Thanks! I'll download the mobile version SDK and test it.

**Comment by andi-at-live2d-com** [comment]
@JiarongYu 
Android is straight-forward to build thanks to CMake, but iOS is a pretty pain to set up... You shouldn't have any problems figuring it out if you have experience with Xcode, but if you run into any issues, just drop a message.

**Comment by andi-at-live2d-com** [comment]
@JiarongYu I hope it's fine for me to close this issue. If you ran into any problems, feel free to re-raise it.
