### ISSUE TITLE
about Live2DCubismSdk.lib 3.0

### ISSUE THREAD

**Issue by 474420502** [Live2D/CubismNativeComponents#7]
we need Live2DCubismSdk.lib 3.0(/MT) to  build Project with visual studio 2015 multi-threaded(/MT). 
but official only supply Live2DCubismSdk.lib 3.0(/MD). 
can you help us for this? @ono-at-live2d-com

**Comment by andi-at-live2d-com** [comment]
@474420502 Thanks for giving Cubism a try!
Linking against the multi-threaded library should be possible. One of our support stuff tested it last week and reported it worked. Could you retry? If it still doesn't work, would it be possible to provide us with a project to reproduce the issue? That would be great.

**Comment by andi-at-live2d-com** [comment]
@474420502 Please allow me to close this issue as fixed (as it should work). Feel free to re-open it if it isn't...

**Comment by 474420502** [comment]
@andi-at-live2d-com we solve the problem。 but /MT(the official example) still not working. 
thanks your help.
ok! close this issue.

**Comment by andi-at-live2d-com** [comment]
@474420502 Thanks for reporting back! Great to hear you solved the problem. I'll have one of my coworkers look at the issue once more just to be sure - maybe they'll find something fishy.
